timeline
  title VANKO Exfiltration Timeline (UTC, 2016)
  2016-04-30 : Classified corpus copied server to OneDrive (MFT copy-signature)
  2016-06-18 : Masquerade 'defaultprinter' created (4720/4724) : temp.zip staged
  2016-06-27 : Merrick recruitment + reply with 3 attachments
  2016-06-29 : 7-Zip archiving (last run 20:26)
  2016-06-30 : 01:28 vacation photos.7z : 01:30 SDelete x10 : 01:46 Dropbox upload : 01:48 Dropbox folder deleted
  2016-11-04 : VSS snapshot + physical image acquired
