mindmap
  root((VANKO IOCs))
    Network
      STARK-FILESERVE share
      192.168.1.5 and .3
      Dropbox acct 984347879
      OneDrive CBDFA76592A9F765
      nina_kwai qq.com
      mmerr001 gmail.com
      im.cas.cn
    Host
      vacation photos.7z b210bcd8
      sdelete.exe / sdelete64.exe
      defaultprinter temp.zip
      SDELETE prefetch deleted
      Level 12 Project Nehemiah
    Accounts
      PC User anthony.vanko
      defaultprinter masquerade
    USB artifact-level
      5650959F StarkResrch
      C83A6C7B Stark-IR
      8C059ED1 drive W
