"""JLECmd wrapper — Eric Zimmerman Windows Jump List parser (Phase 2).

Jump Lists are NTFS-resident shell artefacts that record the
applications and documents a user pinned or recently opened from the
Start menu / taskbar. Two file types live under
``%AppData%\\Microsoft\\Windows\\Recent\\``:

- ``*.automaticDestinations-ms`` — generated by Windows; file-system
  evidence of recently-opened items per AppID.
- ``*.customDestinations-ms``    — generated by applications when they
  override the default Jump List behaviour (e.g. pinning).

Both formats encode CDF-shaped property streams and a list of
``ShellLink`` payloads — the same wire format LECmd parses. JLECmd
flattens both into a CSV plus a per-DestList row CSV that records the
last access timestamp and target path. We surface the flat
``DestList`` rows: those carry the forensic value (``last_access``
+ ``target_full_path`` per recently-opened item).

Pattern mirrors LECmd (``-f`` for file, ``-d`` for directory recurse,
``-q`` to suppress per-file detail dump on stdout, ``--csv <outdir>
--csvf <pinned>`` for tempdir-scoped CSV output). M6.4 graceful skip
on missing dotnet / DLL.
"""

from __future__ import annotations

import asyncio
import csv
import hashlib
import io
import logging
import os
import shutil
import tempfile
from pathlib import Path

from pydantic import BaseModel, Field

from agentropix_mcp._env import get_float, get_int
from agentropix_mcp.wrappers._subprocess import run_with_memory_limit

logger = logging.getLogger(__name__)

DEFAULT_DLL = "/opt/ezt/net9/JLECmd/JLECmd.dll"
DEFAULT_DOTNET = "dotnet"
_OUTPUT_CSV_NAME = "JLECmd_DestList.csv"


def _resolve_dll() -> str:
    return os.environ.get("AGENTROPIX_JLECMD_DLL", DEFAULT_DLL)


def _resolve_dotnet() -> str:
    return os.environ.get("AGENTROPIX_DOTNET_TOOL", DEFAULT_DOTNET)


class JLECmdEntry(BaseModel):
    """One DestList row from a parsed Jump List file.

    JLECmd's DestList CSV records each entry with a ``MRU`` rank, the
    last-access time, the target path, and metadata about the volume
    + interaction (machine ID, hostname, NetBIOS, drive type). For
    forensic timeline reconstruction the salient fields are
    ``last_modified``, ``target_full_path``, and ``arguments`` —
    everything else is provenance.
    """

    source_file: str = ""
    source_created: str = ""
    source_modified: str = ""
    source_accessed: str = ""
    app_id: str = ""
    app_id_description: str = ""
    entry_number: int = 0
    creation_time: str = ""
    last_modified: str = ""
    hostname: str = ""
    mac_address: str = ""
    interaction_count: int = 0
    file_birth_droid_volume: str = ""
    file_birth_droid_file: str = ""
    file_droid_volume: str = ""
    file_droid_file: str = ""
    target_full_path: str = ""
    target_created: str = ""
    target_modified: str = ""
    target_accessed: str = ""
    file_size: int = 0
    arguments: str = ""
    relative_path: str = ""
    working_directory: str = ""
    drive_type: str = ""
    volume_serial: str = ""
    volume_label: str = ""


class JLECmdReport(BaseModel):
    """Parsed JLECmd output (DestList rows aggregated across files).

    Mirrors LECmdReport in shape. ``target_mode`` is ``"file"`` or
    ``"directory"``. ``raw_csv_sha256`` covers chain-of-custody over
    the parsed CSV bytes.
    """

    target: str
    target_mode: str = ""
    entry_count: int = 0
    parsed_count: int = 0
    error_count: int = 0
    truncated: bool = False
    entries: list[JLECmdEntry] = Field(default_factory=list)
    tool: str = "jlecmd"
    raw_stderr: str = ""
    raw_csv_sha256: str = ""
    tool_available: bool = True
    skip_reason: str = ""


def _safe_int(value: str) -> int:
    try:
        return int(value)
    except (ValueError, TypeError):
        return 0


def _parse_jlecmd_csv(
    content: str, *, max_entries: int
) -> tuple[list[JLECmdEntry], int, bool]:
    if not content.strip():
        return [], 0, False

    # EZ Tools framework writes UTF-8 BOM on the first column; strip
    # to keep the first-column lookup honest (lesson from
    # feedback_ez_tools_bom.md).
    content = content.lstrip("﻿")
    reader = csv.DictReader(io.StringIO(content))
    entries: list[JLECmdEntry] = []
    errors = 0
    truncated = False

    for row in reader:
        norm = {
            k.lower().replace(" ", "").strip(): (v or "").strip()
            for k, v in row.items()
            if k
        }
        source_file = norm.get("sourcefile", "")
        if not source_file:
            errors += 1
            continue

        if len(entries) >= max_entries:
            truncated = True
            break

        entries.append(
            JLECmdEntry(
                source_file=source_file,
                source_created=norm.get("sourcecreated", ""),
                source_modified=norm.get("sourcemodified", ""),
                source_accessed=norm.get("sourceaccessed", ""),
                app_id=norm.get("appid", ""),
                app_id_description=norm.get("appiddescription", ""),
                entry_number=_safe_int(norm.get("entrynumber", "0")),
                creation_time=norm.get("creationtime", ""),
                last_modified=norm.get("lastmodified", ""),
                hostname=norm.get("hostname", ""),
                mac_address=norm.get("macaddress", ""),
                interaction_count=_safe_int(norm.get("interactioncount", "0")),
                file_birth_droid_volume=norm.get("filebirthdroidvolume", ""),
                file_birth_droid_file=norm.get("filebirthdroidfile", ""),
                file_droid_volume=norm.get("filedroidvolume", ""),
                file_droid_file=norm.get("filedroidfile", ""),
                target_full_path=norm.get("targetfullpath", "")
                or norm.get("path", ""),
                target_created=norm.get("targetcreated", ""),
                target_modified=norm.get("targetmodified", ""),
                target_accessed=norm.get("targetaccessed", ""),
                file_size=_safe_int(norm.get("filesize", "0")),
                arguments=norm.get("arguments", ""),
                relative_path=norm.get("relativepath", ""),
                working_directory=norm.get("workingdirectory", ""),
                drive_type=norm.get("drivetype", ""),
                volume_serial=norm.get("volumeserialnumber", ""),
                volume_label=norm.get("volumelabel", ""),
            )
        )
    return entries, errors, truncated


async def get_jlecmd(
    target: str | Path,
    *,
    all_files: bool = False,
    timeout: float | None = None,
) -> JLECmdReport:
    """Parse Windows Jump List files via JLECmd (Eric Zimmerman, .NET).

    Args:
        target: Path to a single ``*.automaticDestinations-ms`` /
            ``*.customDestinations-ms`` file, OR a directory containing
            them.
        all_files: When ``target`` is a directory, pass ``--all`` to
            include files that don't match the default Jump-List
            extensions. Ignored in file mode.
        timeout: Subprocess timeout (s). ``None`` reads
            ``AGENTROPIX_JLECMD_TIMEOUT`` (default 120s, floor 5,
            ceiling 3600).

    Raises:
        FileNotFoundError: target missing.
        TimeoutError: JLECmd exceeded timeout.
        RuntimeError: JLECmd returned non-zero with no parseable CSV.

    Graceful skip: missing dotnet or DLL → ``tool_available=False``.
    """
    target_path = Path(target)
    if not target_path.exists():
        raise FileNotFoundError(f"Jump List target not found: {target_path}")

    is_dir = target_path.is_dir()
    target_mode = "directory" if is_dir else "file"

    if timeout is None:
        timeout = get_float(
            "AGENTROPIX_JLECMD_TIMEOUT", 120.0, floor=5.0, ceiling=3600.0
        )
    max_entries = get_int(
        "AGENTROPIX_JLECMD_MAX_ENTRIES", 10_000, floor=1, ceiling=1_000_000
    )

    dotnet_name = _resolve_dotnet()
    dotnet_bin = shutil.which(dotnet_name)
    if not dotnet_bin:
        reason = (
            f"{dotnet_name} not found on PATH; "
            "install dotnet-runtime-9.0 or set AGENTROPIX_DOTNET_TOOL"
        )
        logger.info("JLECmd skipped — %s", reason)
        return JLECmdReport(
            target=str(target_path),
            target_mode=target_mode,
            tool_available=False,
            skip_reason=reason,
        )

    dll_path = Path(_resolve_dll())
    if not dll_path.is_file():
        reason = (
            f"JLECmd DLL not found at {dll_path}; "
            "install via the EZ Tools net9 zip or set AGENTROPIX_JLECMD_DLL"
        )
        logger.info("JLECmd skipped — %s", reason)
        return JLECmdReport(
            target=str(target_path),
            target_mode=target_mode,
            tool_available=False,
            skip_reason=reason,
        )

    with tempfile.TemporaryDirectory(prefix="agentropix-jlecmd-") as tmpdir:
        input_flag = ["-d", str(target_path)] if is_dir else ["-f", str(target_path)]
        cmd = [
            dotnet_bin,
            str(dll_path),
            *input_flag,
            "-q",
            "--csv",
            tmpdir,
            "--csvf",
            _OUTPUT_CSV_NAME,
        ]
        if is_dir and all_files:
            cmd.append("--all")

        logger.info("Running: %s", " ".join(cmd))
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        try:
            _, stderr_bytes = await run_with_memory_limit(proc, timeout, "jlecmd")
        except TimeoutError:
            raise TimeoutError(f"JLECmd timed out after {timeout}s") from None

        stderr = stderr_bytes.decode(errors="replace")

        # JLECmd writes one or more CSVs into tmpdir; the canonical
        # DestList one matches the pinned name. Other files (per-AppID
        # / Lnk listings) we ignore for the flat surface.
        out_csv = Path(tmpdir) / _OUTPUT_CSV_NAME
        if not out_csv.is_file():
            # JLECmd version variations: name might be prefixed.
            candidates = [
                p for p in Path(tmpdir).iterdir()
                if p.is_file() and p.suffix.lower() == ".csv"
            ]
            if candidates:
                out_csv = candidates[0]

        csv_bytes = out_csv.read_bytes() if out_csv.is_file() else b""
        if proc.returncode != 0 and not csv_bytes:
            raise RuntimeError(
                f"JLECmd failed (rc={proc.returncode}): {stderr[:500]}"
            )

        csv_text = csv_bytes.decode(errors="replace") if csv_bytes else ""
        entries, error_count, truncated = _parse_jlecmd_csv(
            csv_text, max_entries=max_entries
        )
        return JLECmdReport(
            target=str(target_path),
            target_mode=target_mode,
            entry_count=len(entries),
            parsed_count=len(entries),
            error_count=error_count,
            truncated=truncated,
            entries=entries,
            raw_stderr=stderr[:1000] if stderr else "",
            raw_csv_sha256=hashlib.sha256(csv_bytes).hexdigest() if csv_bytes else "",
        )
